### ISSUE TITLE
Error on websocket close

### ISSUE THREAD

**Issue by dfee** [subyraman/sanic_compress#1]
When a websocket connection is closed, I get the following error:
```
ERROR 2017-03-16 19:26:54,394 [sanic:72][MainThread] Traceback (most recent call last):
  File "/Users/dfee/code/spark/env/lib/python3.6/site-packages/sanic/app.py", line 470, in handle_request
    _response = await _response
  File "/Users/dfee/code/spark/env/lib/python3.6/site-packages/sanic_compress/__init__.py", line 27, in compress_response
    return (await self._compress_response(request, response))
  File "/Users/dfee/code/spark/env/lib/python3.6/site-packages/sanic_compress/__init__.py", line 31, in _compress_response
    content_length = len(response.body)
AttributeError: 'NoneType' object has no attribute 'body'
```

websocket is now supported in the HEAD of sanic, by the way!

**Comment by subyraman** [comment]
Hrm I will take a look, but you might want to avoid gzipping your websocket routes regardless.
